[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = "^3.10"
seaborn = "*"
numpy = '1.26.3'
matplotlib = "^3.8.2"
